export const DELHI_NCR_STATIONS = [
  { id: 201, title: "Statiq Superfast Charging Hub - Cyber City", operator: "Statiq", address: "DLF Cyber City, Phase 2, Sector 24", region: "Gurugram", lat: 28.4950, lng: 77.0895, type: "DC_FAST", kw: 60, price: "₹18.50 / kWh", connectors: ["CCS-2", "GB/T"], available: 3, total: 4, votes: 12 },
  { id: 202, title: "Tata Power EZ Charge - Aerocity Hub", operator: "Tata Power", address: "Worldmark 3, Aerocity", region: "Delhi", lat: 28.5562, lng: 77.1200, type: "DC_FAST", kw: 120, price: "₹21.00 / kWh", connectors: ["CCS-2", "CHAdeMO"], available: 5, total: 6, votes: 45 },
  { id: 203, title: "Delhi Transco Charging Station - CP", operator: "Delhi Transco Ltd", address: "Inner Circle, Connaught Place", region: "Delhi", lat: 28.6315, lng: 77.2167, type: "DC_FAST", kw: 50, price: "₹15.00 / kWh", connectors: ["CCS-2", "Type 2"], available: 2, total: 2, votes: 8 },
  { id: 204, title: "Statiq Charging Hub - Noida Sector 18", operator: "Statiq", address: "Near DLF Mall of India, Sector 18", region: "Noida", lat: 28.5672, lng: 77.3211, type: "DC_FAST", kw: 60, price: "₹17.50 / kWh", connectors: ["CCS-2", "GB/T"], available: 4, total: 4, votes: 22 },
  { id: 205, title: "Greater Noida Alpha 1 EV Charger", operator: "ChargePoint India", address: "Commercial Belt, Alpha 1", region: "Noida", lat: 28.4744, lng: 77.5040, type: "AC_SLOW", kw: 22, price: "₹14.00 / kWh", connectors: ["Type 2 AC"], available: 2, total: 3, votes: 3 },
  { id: 206, title: "Ather Grid - MG Road Hub", operator: "Ather Grid", address: "MG Road Metro Station", region: "Gurugram", lat: 28.4795, lng: 77.0801, type: "AC_SLOW", kw: 15, price: "₹13.50 / kWh", connectors: ["Ather Pod", "Type 2"], available: 1, total: 2, votes: 19 },
  { id: 207, title: "Zeon Fast Charger - Indirapuram", operator: "Zeon Charging", address: "Shipra Mall, Indirapuram", region: "Ghaziabad", lat: 28.6360, lng: 77.3705, type: "DC_FAST", kw: 50, price: "₹19.00 / kWh", connectors: ["CCS-2"], available: 3, total: 4, votes: 7 },
  { id: 208, title: "EESL Public Charging Hub - Nehru Place", operator: "EESL / Convergence", address: "Nehru Place Bus Terminal", region: "Delhi", lat: 28.5492, lng: 77.2519, type: "DC_FAST", kw: 60, price: "₹15.50 / kWh", connectors: ["CCS-2", "GB/T"], available: 6, total: 8, votes: 31 },
];
